### ISSUE TITLE
Mod items preventing other items from spawning

### ISSUE THREAD

**Issue by OddJarro** [Buuz135/SushiGoCrafting#13]
Avocado trees have completely infested the world. Orange trees, apple trees, grapes, bananas, etc, are not spawning. Instead, every tree is an avocado tree. This is annoying and I can't figure out how to fix it. This is especially bad because we have the solcarrot mod and can't eat those foods. Also, the seeds from this mod keep replacing the seeds from simple farming. This is a horrible mod when it comes to coexisting with other mods.

**Comment by Buuz135** [comment]
Enigmatica 6 has all the mods/features you mentions and there is no issue.

**Comment by OddJarro** [comment]
This is the mod I am playing and that is where the problem is. How can you close this when it isn't resolved?

**Comment by MuteTiefling** [comment]
> This is a horrible mod when it comes to coexisting with other mods.

A bit of politeness goes a long way. Calling a mod horrible and expecting a fix is a bit... well. Rude.

But as Buuz has said, Enigmatica 6 is having no issues with sushigo crafting co-existing with the other mods you've mentioned. Your best bet would be to use a binary search method to determine which mods -exactly- cause the issue. Then you can report it politely to the proper places.
