### ISSUE TITLE
Enigmatica 6 has all the mods/features you mention and there is no issue.

### ISSUE THREAD

**Issue by OddJarro** [Buuz135/SushiGoCrafting#14]
Enigmatica 6 has all the mods/features you mention and there is no issue.

_Originally posted by @Buuz135 in https://github.com/Buuz135/SushiGoCrafting/issues/13#issuecomment-871723400_

This is literally the mod where I am experiencing this issue. Not sure why you took the liberty of closing the previous issue without helping at all or asking any questions.

**Comment by Buuz135** [comment]
I literally can't replicate it in a big modpack. You are just probably overexagerating. Discord exists for support and better communication.

**Comment by OddJarro** [comment]
Lmao, I am overexaggerating? Dude, what kind of garbage responses are these? Im telling what is happening in the world with you shit mod and you tell me I am doing something wrong. Those are the only trees spawning in the world. Every new chunk where fruit trees spawn, only those are spawning. Nothing else. When I break grass, the only seeds coming out are from sushigocraft. Not sure why you are being such a dick with your responses.

**Comment by Buuz135** [comment]
I can't help you when you have never provided:

1) Mod versions
2) Forge versions
3) Proof of the issue
4) Modlist

**Comment by WBgroup** [comment]
Yes, you might be exaggerating, I had problems with finding Avocado trees in E6, yes - seeds might be _too common_, but your responses don't help with finding a way of replicating nor finding where is the issue when the only thing you said is that it replaces _some mod's fruit trees_ with Sushigocrafting avocado trees.
