### ISSUE TITLE
[1.18.2] Kelp is used in all of the recipes and Seaweed isnt

### ISSUE THREAD

**Issue by Peach774** [Buuz135/SushiGoCrafting#29]
As title - seaweed should be used in the recipes. As it stands currently, seaweed has no use at all since all of the recipes use kelp instead.

**Comment by BitBlitObviMormon** [comment]
Another way to handle this could be removing seaweed spawns entirely and using kelp as the new seaweed.

**Comment by Buuz135** [comment]
Changed in 1.20
