### ISSUE TITLE
Server crash due to ticking fermenting barrel

### ISSUE THREAD

**Issue by TheDarkPreacher** [Buuz135/SushiGoCrafting#30]
Reported issue on FTB Forum, hopefully the FTB team sees it soon. [Here is the link to that post](https://forum.feed-the-beast.com/threads/dw20-1-18-ver-1-4-0-sushi-go-crafting-crash.305593/). 
To sum up: Updated server to 1.4.0 of DW20 1.18, player joined, server crash, ticking tile entity. Crash report is [here](https://gist.github.com/TheDarkPreacher/2ecb4d2bcfaac2931e09ebf2941a4ad7). Enabled Forge Erroring Entity removal, server restarted. Player could not interact with barrel, attempted to make a new barrel, client crash to desktop.

**Comment by Buuz135** [comment]
Already fixed, please update SGC
