### ISSUE TITLE
Roller not working

### ISSUE THREAD

**Issue by Flowylege** [Buuz135/SushiGoCrafting#34]
Hello, I have an issue with my roller : I cannot do anything with it.
It is stuck on the "maki" and I cannot change the sushi type ; I cannot change the ingredients' weight I wanna put in, and I cannot roll anything, cause when I click on all of these buttons, nothing is happening. 

Is it normal, how can I fix it ?

**Comment by Buuz135** [comment]
What mod version of titanium and Sushi Go Crafting do you have?

**Comment by Flowylege** [comment]
I have Titanium 3.6.1-13 and idk about Sushi Go crafting cause it's not written, but both are for Minecraft 1.19.2

**Comment by Buuz135** [comment]
Update titanium, you are like 13 version behind

**Comment by Flowylege** [comment]
The latest Titanium makes my Minecraft crash, I have the exit-code -1, and having an older version is the only way it is not crashing
