### ISSUE TITLE
Newest update crashes on dedicated servers.

### ISSUE THREAD

**Issue by SquirrelKiev** [Buuz135/SushiGoCrafting#40]
**SushiGoCrafting Version:**
1.20.1-0.5.0
**Titanium Version:**
1.20.1-3.8.25
**Crashlog If Applicable (Upload to pastebin/gist):**
https://pastebin.com/Jks1HZLA

**Comment by Buuz135** [comment]
https://github.com/Buuz135/SushiGoCrafting/commit/97db4c323e5ca6110e21e0c9c5c5c09a2c50f2d9
