### ISSUE TITLE
Crash when mousing over items rewarded from a loot table.

### ISSUE THREAD

**Issue by MuteTiefling** [Buuz135/SushiGoCrafting#9]
Crash when mousing over items rewarded from a loot table.

Crafted a perfect tobiko crab cheese california. NBT output: 
![image](https://user-images.githubusercontent.com/9543430/120123191-70a60a00-c17b-11eb-84a5-38806448214b.png)

Got the item from loot table, NBT appears identical:
![image](https://user-images.githubusercontent.com/9543430/120123202-81568000-c17b-11eb-80bb-93c6899c3883.png)

Crash log: 
[crash-2021-05-30_19.12.17-client.txt](https://github.com/Buuz135/SushiGoCrafting/files/6567040/crash-2021-05-30_19.12.17-client.txt)

JSON for the loot table
[quest_farmers_delight.txt](https://github.com/Buuz135/SushiGoCrafting/files/6567042/quest_farmers_delight.txt)

**Comment by Buuz135** [comment]
To have proper nbt you will need to define the nbt with its type like this `/give Dev sushigocrafting:tobiko_crab_cheese_california{Weights:[I;0,0,0,0,0,0],Spices:{wasabi:1b,soy_sauce:1b}} 1`
This way you define that `Weights` its an `IntArray` and Spices are `booleans`

**Comment by MuteTiefling** [comment]
Cool, thanks
